clk: Fix mismerge that breaks compile when debug is disabled
Error appears when DEBUG_KERNEL and DEBUG_FS is disabled:
../drivers/clk/clk.c:4007:15: error: use of undeclared identifier 'all_lists'
        for (lists = all_lists; *lists; lists++)

The offending commit is f114a36, re-applied it again and re-added bd09703.